s=set()
n=input("ENter the number:")
s.add(int(n))
n=input("ENter the number:")
s.add(int(n))
n=input("ENter the number:")
s.add(int(n))
n=input("ENter the number:")
s.add(int(n))
n=input("ENter the number:")
s.add(int(n))
n=input("ENter the number:")
s.add(int(n))
n=input("ENter the number:")
s.add(int(n))
n=input("ENter the number:")
s.add(int(n))


print(s)